//
//  StyleKit.m
//  Password Factory
//
//  Created by Cristiana Yambo on 11/16/17.
//  Copyright © 2017 Password Factory. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import "StyleKit.h"


@implementation StyleKit

#pragma mark Cache

static NSImage* _imageOfPreferencesButton = nil;
static NSImage* _imageOfMenuIcon = nil;
static NSImage* _imageOfZoom1 = nil;
static NSImage* _imageOfZoom = nil;
static NSImage* _imageOfPasswordHeader = nil;
static NSImage* _imageOfPasswordStrengthHeader = nil;
static NSImage* _imageOfPasswordTypeHeader = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawStrengthMeterWithStrengthColor: (NSColor*)strengthColor strength: (CGFloat)strength size: (NSSize)size
{
    [StyleKit drawStrengthMeterWithFrame: NSMakeRect(0, 0, 400, 50) resizing: StyleKitResizingBehaviorAspectFit strengthColor: strengthColor strength: strength size: size];
}

+ (void)drawStrengthMeterWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing strengthColor: (NSColor*)strengthColor strength: (CGFloat)strength size: (NSSize)size
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 400, 50), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 400, resizedFrame.size.height / 50);


    //// Strength Level Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextScaleCTM(context, strength, 1);

    NSBezierPath* strengthLevelPath = [NSBezierPath bezierPathWithRect: NSMakeRect(0, 0, size.width, size.height)];
    [strengthColor setFill];
    [strengthLevelPath fill];

    [NSGraphicsContext restoreGraphicsState];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawPreferencesButton
{
    //// Color Declarations
    NSColor* strokeColor = [NSColor colorWithRed: 0.31 green: 0.678 blue: 0.984 alpha: 1];

    //// Bezier Drawing
    NSBezierPath* bezierPath = [NSBezierPath bezierPath];
    [bezierPath moveToPoint: NSMakePoint(21, 13.67)];
    [bezierPath curveToPoint: NSMakePoint(13.67, 21) controlPoint1: NSMakePoint(16.95, 13.67) controlPoint2: NSMakePoint(13.67, 16.95)];
    [bezierPath curveToPoint: NSMakePoint(21, 28.33) controlPoint1: NSMakePoint(13.67, 25.05) controlPoint2: NSMakePoint(16.95, 28.33)];
    [bezierPath curveToPoint: NSMakePoint(28.33, 21) controlPoint1: NSMakePoint(25.05, 28.33) controlPoint2: NSMakePoint(28.33, 25.05)];
    [bezierPath curveToPoint: NSMakePoint(21, 13.67) controlPoint1: NSMakePoint(28.33, 16.95) controlPoint2: NSMakePoint(25.05, 13.67)];
    [bezierPath closePath];
    [bezierPath moveToPoint: NSMakePoint(40, 18.16)];
    [bezierPath curveToPoint: NSMakePoint(40.5, 18.9) controlPoint1: NSMakePoint(40.27, 18.27) controlPoint2: NSMakePoint(40.5, 18.6)];
    [bezierPath lineToPoint: NSMakePoint(40.5, 23.1)];
    [bezierPath curveToPoint: NSMakePoint(40, 23.84) controlPoint1: NSMakePoint(40.5, 23.4) controlPoint2: NSMakePoint(40.27, 23.73)];
    [bezierPath lineToPoint: NSMakePoint(36.16, 25.38)];
    [bezierPath curveToPoint: NSMakePoint(35.48, 26.09) controlPoint1: NSMakePoint(35.88, 25.49) controlPoint2: NSMakePoint(35.58, 25.81)];
    [bezierPath lineToPoint: NSMakePoint(34.83, 27.64)];
    [bezierPath curveToPoint: NSMakePoint(34.81, 28.62) controlPoint1: NSMakePoint(34.71, 27.91) controlPoint2: NSMakePoint(34.7, 28.35)];
    [bezierPath lineToPoint: NSMakePoint(36.44, 32.43)];
    [bezierPath curveToPoint: NSMakePoint(36.27, 33.3) controlPoint1: NSMakePoint(36.56, 32.7) controlPoint2: NSMakePoint(36.48, 33.09)];
    [bezierPath lineToPoint: NSMakePoint(33.3, 36.27)];
    [bezierPath curveToPoint: NSMakePoint(32.43, 36.44) controlPoint1: NSMakePoint(33.09, 36.48) controlPoint2: NSMakePoint(32.7, 36.56)];
    [bezierPath lineToPoint: NSMakePoint(28.62, 34.81)];
    [bezierPath curveToPoint: NSMakePoint(27.64, 34.83) controlPoint1: NSMakePoint(28.35, 34.7) controlPoint2: NSMakePoint(27.91, 34.71)];
    [bezierPath lineToPoint: NSMakePoint(26.09, 35.48)];
    [bezierPath curveToPoint: NSMakePoint(25.38, 36.16) controlPoint1: NSMakePoint(25.81, 35.58) controlPoint2: NSMakePoint(25.49, 35.88)];
    [bezierPath lineToPoint: NSMakePoint(23.84, 40)];
    [bezierPath curveToPoint: NSMakePoint(23.1, 40.5) controlPoint1: NSMakePoint(23.73, 40.27) controlPoint2: NSMakePoint(23.4, 40.5)];
    [bezierPath lineToPoint: NSMakePoint(18.9, 40.5)];
    [bezierPath curveToPoint: NSMakePoint(18.16, 40) controlPoint1: NSMakePoint(18.6, 40.5) controlPoint2: NSMakePoint(18.27, 40.27)];
    [bezierPath lineToPoint: NSMakePoint(16.62, 36.16)];
    [bezierPath curveToPoint: NSMakePoint(15.91, 35.48) controlPoint1: NSMakePoint(16.51, 35.88) controlPoint2: NSMakePoint(16.19, 35.58)];
    [bezierPath lineToPoint: NSMakePoint(14.36, 34.83)];
    [bezierPath curveToPoint: NSMakePoint(13.38, 34.81) controlPoint1: NSMakePoint(14.09, 34.71) controlPoint2: NSMakePoint(13.65, 34.7)];
    [bezierPath lineToPoint: NSMakePoint(9.57, 36.44)];
    [bezierPath curveToPoint: NSMakePoint(8.7, 36.27) controlPoint1: NSMakePoint(9.3, 36.56) controlPoint2: NSMakePoint(8.91, 36.48)];
    [bezierPath lineToPoint: NSMakePoint(5.73, 33.3)];
    [bezierPath curveToPoint: NSMakePoint(5.56, 32.43) controlPoint1: NSMakePoint(5.52, 33.09) controlPoint2: NSMakePoint(5.44, 32.7)];
    [bezierPath lineToPoint: NSMakePoint(7.19, 28.62)];
    [bezierPath curveToPoint: NSMakePoint(7.17, 27.64) controlPoint1: NSMakePoint(7.3, 28.35) controlPoint2: NSMakePoint(7.29, 27.91)];
    [bezierPath lineToPoint: NSMakePoint(6.52, 26.09)];
    [bezierPath curveToPoint: NSMakePoint(5.84, 25.38) controlPoint1: NSMakePoint(6.42, 25.81) controlPoint2: NSMakePoint(6.12, 25.49)];
    [bezierPath lineToPoint: NSMakePoint(2, 23.84)];
    [bezierPath curveToPoint: NSMakePoint(1.5, 23.1) controlPoint1: NSMakePoint(1.73, 23.73) controlPoint2: NSMakePoint(1.5, 23.4)];
    [bezierPath lineToPoint: NSMakePoint(1.5, 18.9)];
    [bezierPath curveToPoint: NSMakePoint(2, 18.16) controlPoint1: NSMakePoint(1.5, 18.6) controlPoint2: NSMakePoint(1.73, 18.27)];
    [bezierPath lineToPoint: NSMakePoint(5.84, 16.62)];
    [bezierPath curveToPoint: NSMakePoint(6.52, 15.91) controlPoint1: NSMakePoint(6.12, 16.51) controlPoint2: NSMakePoint(6.42, 16.19)];
    [bezierPath lineToPoint: NSMakePoint(7.17, 14.36)];
    [bezierPath curveToPoint: NSMakePoint(7.19, 13.38) controlPoint1: NSMakePoint(7.29, 14.09) controlPoint2: NSMakePoint(7.3, 13.65)];
    [bezierPath lineToPoint: NSMakePoint(5.56, 9.57)];
    [bezierPath curveToPoint: NSMakePoint(5.73, 8.7) controlPoint1: NSMakePoint(5.44, 9.3) controlPoint2: NSMakePoint(5.52, 8.91)];
    [bezierPath lineToPoint: NSMakePoint(8.7, 5.73)];
    [bezierPath curveToPoint: NSMakePoint(9.57, 5.56) controlPoint1: NSMakePoint(8.91, 5.52) controlPoint2: NSMakePoint(9.3, 5.44)];
    [bezierPath lineToPoint: NSMakePoint(13.38, 7.19)];
    [bezierPath curveToPoint: NSMakePoint(14.36, 7.17) controlPoint1: NSMakePoint(13.65, 7.3) controlPoint2: NSMakePoint(14.09, 7.29)];
    [bezierPath lineToPoint: NSMakePoint(15.91, 6.52)];
    [bezierPath curveToPoint: NSMakePoint(16.62, 5.84) controlPoint1: NSMakePoint(16.19, 6.42) controlPoint2: NSMakePoint(16.51, 6.12)];
    [bezierPath lineToPoint: NSMakePoint(18.16, 2)];
    [bezierPath curveToPoint: NSMakePoint(18.9, 1.5) controlPoint1: NSMakePoint(18.27, 1.73) controlPoint2: NSMakePoint(18.6, 1.5)];
    [bezierPath lineToPoint: NSMakePoint(23.1, 1.5)];
    [bezierPath curveToPoint: NSMakePoint(23.84, 2) controlPoint1: NSMakePoint(23.4, 1.5) controlPoint2: NSMakePoint(23.73, 1.73)];
    [bezierPath lineToPoint: NSMakePoint(25.38, 5.84)];
    [bezierPath curveToPoint: NSMakePoint(26.09, 6.52) controlPoint1: NSMakePoint(25.49, 6.12) controlPoint2: NSMakePoint(25.81, 6.42)];
    [bezierPath lineToPoint: NSMakePoint(27.64, 7.17)];
    [bezierPath curveToPoint: NSMakePoint(28.62, 7.19) controlPoint1: NSMakePoint(27.91, 7.29) controlPoint2: NSMakePoint(28.35, 7.3)];
    [bezierPath lineToPoint: NSMakePoint(32.43, 5.56)];
    [bezierPath curveToPoint: NSMakePoint(33.3, 5.73) controlPoint1: NSMakePoint(32.7, 5.44) controlPoint2: NSMakePoint(33.09, 5.52)];
    [bezierPath lineToPoint: NSMakePoint(36.27, 8.7)];
    [bezierPath curveToPoint: NSMakePoint(36.44, 9.57) controlPoint1: NSMakePoint(36.48, 8.91) controlPoint2: NSMakePoint(36.56, 9.3)];
    [bezierPath lineToPoint: NSMakePoint(34.81, 13.38)];
    [bezierPath curveToPoint: NSMakePoint(34.83, 14.36) controlPoint1: NSMakePoint(34.7, 13.65) controlPoint2: NSMakePoint(34.71, 14.09)];
    [bezierPath lineToPoint: NSMakePoint(35.48, 15.91)];
    [bezierPath curveToPoint: NSMakePoint(36.16, 16.62) controlPoint1: NSMakePoint(35.58, 16.19) controlPoint2: NSMakePoint(35.88, 16.51)];
    [bezierPath lineToPoint: NSMakePoint(40, 18.16)];
    [bezierPath closePath];
    [strokeColor setStroke];
    bezierPath.lineWidth = 2;
    [bezierPath stroke];
}

+ (void)drawMenuIcon
{

    //// Bezier Drawing
    NSBezierPath* bezierPath = [NSBezierPath bezierPath];
    [bezierPath moveToPoint: NSMakePoint(23.74, 10.34)];
    [bezierPath lineToPoint: NSMakePoint(16.84, 17.24)];
    [bezierPath curveToPoint: NSMakePoint(17.54, 19.18) controlPoint1: NSMakePoint(17.21, 17.86) controlPoint2: NSMakePoint(17.44, 18.52)];
    [bezierPath curveToPoint: NSMakePoint(17.58, 19.41) controlPoint1: NSMakePoint(17.56, 19.26) controlPoint2: NSMakePoint(17.57, 19.34)];
    [bezierPath curveToPoint: NSMakePoint(17.58, 19.47) controlPoint1: NSMakePoint(17.58, 19.43) controlPoint2: NSMakePoint(17.58, 19.45)];
    [bezierPath curveToPoint: NSMakePoint(17.37, 21.37) controlPoint1: NSMakePoint(17.64, 20.13) controlPoint2: NSMakePoint(17.57, 20.78)];
    [bezierPath curveToPoint: NSMakePoint(16.45, 22.84) controlPoint1: NSMakePoint(17.18, 21.92) controlPoint2: NSMakePoint(16.87, 22.42)];
    [bezierPath curveToPoint: NSMakePoint(12.86, 23.95) controlPoint1: NSMakePoint(15.51, 23.78) controlPoint2: NSMakePoint(14.2, 24.14)];
    [bezierPath curveToPoint: NSMakePoint(9.68, 22.32) controlPoint1: NSMakePoint(11.74, 23.8) controlPoint2: NSMakePoint(10.6, 23.25)];
    [bezierPath curveToPoint: NSMakePoint(8.07, 17.69) controlPoint1: NSMakePoint(8.35, 21) controlPoint2: NSMakePoint(7.8, 19.23)];
    [bezierPath curveToPoint: NSMakePoint(9.16, 15.55) controlPoint1: NSMakePoint(8.2, 16.89) controlPoint2: NSMakePoint(8.57, 16.14)];
    [bezierPath curveToPoint: NSMakePoint(9.36, 15.36) controlPoint1: NSMakePoint(9.22, 15.49) controlPoint2: NSMakePoint(9.29, 15.42)];
    [bezierPath curveToPoint: NSMakePoint(12.47, 14.41) controlPoint1: NSMakePoint(10.21, 14.63) controlPoint2: NSMakePoint(11.33, 14.32)];
    [bezierPath curveToPoint: NSMakePoint(14.06, 14.81) controlPoint1: NSMakePoint(13, 14.46) controlPoint2: NSMakePoint(13.54, 14.59)];
    [bezierPath lineToPoint: NSMakePoint(14.36, 14.51)];
    [bezierPath curveToPoint: NSMakePoint(14.36, 13.47) controlPoint1: NSMakePoint(14.36, 14.51) controlPoint2: NSMakePoint(13.84, 13.99)];
    [bezierPath curveToPoint: NSMakePoint(15.41, 13.47) controlPoint1: NSMakePoint(14.89, 12.95) controlPoint2: NSMakePoint(15.41, 13.47)];
    [bezierPath lineToPoint: NSMakePoint(15.93, 13.99)];
    [bezierPath lineToPoint: NSMakePoint(17.75, 12.17)];
    [bezierPath lineToPoint: NSMakePoint(18.79, 12.17)];
    [bezierPath lineToPoint: NSMakePoint(19.05, 11.91)];
    [bezierPath lineToPoint: NSMakePoint(19.05, 10.86)];
    [bezierPath lineToPoint: NSMakePoint(21.14, 8.78)];
    [bezierPath lineToPoint: NSMakePoint(21.66, 8.78)];
    [bezierPath lineToPoint: NSMakePoint(22.44, 8)];
    [bezierPath lineToPoint: NSMakePoint(24, 8)];
    [bezierPath lineToPoint: NSMakePoint(23.74, 10.34)];
    [bezierPath closePath];
    [bezierPath moveToPoint: NSMakePoint(11.22, 20.78)];
    [bezierPath curveToPoint: NSMakePoint(12.78, 20.78) controlPoint1: NSMakePoint(11.65, 21.21) controlPoint2: NSMakePoint(12.35, 21.21)];
    [bezierPath curveToPoint: NSMakePoint(12.78, 19.22) controlPoint1: NSMakePoint(13.21, 20.35) controlPoint2: NSMakePoint(13.21, 19.65)];
    [bezierPath curveToPoint: NSMakePoint(11.22, 19.22) controlPoint1: NSMakePoint(12.35, 18.79) controlPoint2: NSMakePoint(11.65, 18.79)];
    [bezierPath curveToPoint: NSMakePoint(11.22, 20.78) controlPoint1: NSMakePoint(10.79, 19.65) controlPoint2: NSMakePoint(10.79, 20.35)];
    [bezierPath closePath];
    [NSColor.blackColor setStroke];
    bezierPath.lineWidth = 1;
    [bezierPath stroke];
}

+ (void)drawStrengthBoxWithStrengthColor: (NSColor*)strengthColor
{

    //// Rectangle Drawing
    NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRect: NSMakeRect(0, 0, 22, 22)];
    [strengthColor setFill];
    [rectanglePath fill];
}

+ (void)drawAdvancedTypeWithTypeColor: (NSColor*)typeColor
{
    [StyleKit drawAdvancedTypeWithFrame: NSMakeRect(0, 0, 250, 250) resizing: StyleKitResizingBehaviorAspectFit typeColor: typeColor];
}

+ (void)drawAdvancedTypeWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing typeColor: (NSColor*)typeColor
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 250, 250), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 250, resizedFrame.size.height / 250);


    //// Polygon Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 51, 201);
    CGContextRotateCTM(context, 30 * M_PI/180);

    NSBezierPath* polygonPath = [NSBezierPath bezierPath];
    [polygonPath moveToPoint: NSMakePoint(0, 28.3)];
    [polygonPath lineToPoint: NSMakePoint(24.51, 14.15)];
    [polygonPath lineToPoint: NSMakePoint(24.51, -14.15)];
    [polygonPath lineToPoint: NSMakePoint(0, -28.3)];
    [polygonPath lineToPoint: NSMakePoint(-24.51, -14.15)];
    [polygonPath lineToPoint: NSMakePoint(-24.51, 14.15)];
    [polygonPath closePath];
    [typeColor setStroke];
    polygonPath.lineWidth = 15;
    [polygonPath stroke];

    [NSGraphicsContext restoreGraphicsState];


    //// Polygon 2 Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 48.3, 55.5);
    CGContextRotateCTM(context, 30 * M_PI/180);

    NSBezierPath* polygon2Path = [NSBezierPath bezierPath];
    [polygon2Path moveToPoint: NSMakePoint(0, 28.3)];
    [polygon2Path lineToPoint: NSMakePoint(24.51, 14.15)];
    [polygon2Path lineToPoint: NSMakePoint(24.51, -14.15)];
    [polygon2Path lineToPoint: NSMakePoint(0, -28.3)];
    [polygon2Path lineToPoint: NSMakePoint(-24.51, -14.15)];
    [polygon2Path lineToPoint: NSMakePoint(-24.51, 14.15)];
    [polygon2Path closePath];
    [typeColor setStroke];
    polygon2Path.lineWidth = 15;
    [polygon2Path stroke];

    [NSGraphicsContext restoreGraphicsState];


    //// Polygon 3 Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 151.7, 197.5);
    CGContextRotateCTM(context, 30 * M_PI/180);

    NSBezierPath* polygon3Path = [NSBezierPath bezierPath];
    [polygon3Path moveToPoint: NSMakePoint(0, 28.3)];
    [polygon3Path lineToPoint: NSMakePoint(24.51, 14.15)];
    [polygon3Path lineToPoint: NSMakePoint(24.51, -14.15)];
    [polygon3Path lineToPoint: NSMakePoint(0, -28.3)];
    [polygon3Path lineToPoint: NSMakePoint(-24.51, -14.15)];
    [polygon3Path lineToPoint: NSMakePoint(-24.51, 14.15)];
    [polygon3Path closePath];
    [typeColor setStroke];
    polygon3Path.lineWidth = 15;
    [polygon3Path stroke];

    [NSGraphicsContext restoreGraphicsState];


    //// Polygon 4 Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 93.7, 118.5);
    CGContextRotateCTM(context, 30 * M_PI/180);

    NSBezierPath* polygon4Path = [NSBezierPath bezierPath];
    [polygon4Path moveToPoint: NSMakePoint(0, 28.3)];
    [polygon4Path lineToPoint: NSMakePoint(24.51, 14.15)];
    [polygon4Path lineToPoint: NSMakePoint(24.51, -14.15)];
    [polygon4Path lineToPoint: NSMakePoint(0, -28.3)];
    [polygon4Path lineToPoint: NSMakePoint(-24.51, -14.15)];
    [polygon4Path lineToPoint: NSMakePoint(-24.51, 14.15)];
    [polygon4Path closePath];
    [typeColor setStroke];
    polygon4Path.lineWidth = 15;
    [polygon4Path stroke];

    [NSGraphicsContext restoreGraphicsState];


    //// Polygon 5 Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 138.3, 44.5);
    CGContextRotateCTM(context, 30 * M_PI/180);

    NSBezierPath* polygon5Path = [NSBezierPath bezierPath];
    [polygon5Path moveToPoint: NSMakePoint(0, 28.3)];
    [polygon5Path lineToPoint: NSMakePoint(24.51, 14.15)];
    [polygon5Path lineToPoint: NSMakePoint(24.51, -14.15)];
    [polygon5Path lineToPoint: NSMakePoint(0, -28.3)];
    [polygon5Path lineToPoint: NSMakePoint(-24.51, -14.15)];
    [polygon5Path lineToPoint: NSMakePoint(-24.51, 14.15)];
    [polygon5Path closePath];
    [typeColor setStroke];
    polygon5Path.lineWidth = 15;
    [polygon5Path stroke];

    [NSGraphicsContext restoreGraphicsState];


    //// Polygon 6 Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 211.7, 94.5);
    CGContextRotateCTM(context, 30 * M_PI/180);

    NSBezierPath* polygon6Path = [NSBezierPath bezierPath];
    [polygon6Path moveToPoint: NSMakePoint(0, 28.3)];
    [polygon6Path lineToPoint: NSMakePoint(24.51, 14.15)];
    [polygon6Path lineToPoint: NSMakePoint(24.51, -14.15)];
    [polygon6Path lineToPoint: NSMakePoint(0, -28.3)];
    [polygon6Path lineToPoint: NSMakePoint(-24.51, -14.15)];
    [polygon6Path lineToPoint: NSMakePoint(-24.51, 14.15)];
    [polygon6Path closePath];
    [typeColor setStroke];
    polygon6Path.lineWidth = 15;
    [polygon6Path stroke];

    [NSGraphicsContext restoreGraphicsState];


    //// Bezier Drawing
    NSBezierPath* bezierPath = [NSBezierPath bezierPath];
    [bezierPath moveToPoint: NSMakePoint(137.57, 173)];
    [bezierPath lineToPoint: NSMakePoint(107.86, 143)];
    [typeColor setStroke];
    bezierPath.lineWidth = 15;
    [bezierPath stroke];


    //// Bezier 2 Drawing
    NSBezierPath* bezier2Path = [NSBezierPath bezierPath];
    [bezier2Path moveToPoint: NSMakePoint(65.14, 176.5)];
    [bezier2Path lineToPoint: NSMakePoint(79.57, 143)];
    [typeColor setStroke];
    bezier2Path.lineWidth = 15;
    [bezier2Path stroke];


    //// Bezier 3 Drawing
    NSBezierPath* bezier3Path = [NSBezierPath bezierPath];
    [bezier3Path moveToPoint: NSMakePoint(76.57, 55.5)];
    [bezier3Path lineToPoint: NSMakePoint(110, 44.49)];
    [typeColor setStroke];
    bezier3Path.lineWidth = 15;
    [bezier3Path stroke];


    //// Bezier 4 Drawing
    NSBezierPath* bezier4Path = [NSBezierPath bezierPath];
    [bezier4Path moveToPoint: NSMakePoint(166.57, 44.5)];
    [bezier4Path lineToPoint: NSMakePoint(197.57, 70)];
    [typeColor setStroke];
    bezier4Path.lineWidth = 15;
    [bezier4Path stroke];


    //// Bezier 5 Drawing
    NSBezierPath* bezier5Path = [NSBezierPath bezierPath];
    [bezier5Path moveToPoint: NSMakePoint(107.86, 94.01)];
    [bezier5Path lineToPoint: NSMakePoint(124.14, 68.99)];
    [typeColor setStroke];
    bezier5Path.lineWidth = 15;
    [bezier5Path stroke];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawPassphraseTypeWithTypeColor: (NSColor*)typeColor
{
    [StyleKit drawPassphraseTypeWithFrame: NSMakeRect(0, 0, 250, 250) resizing: StyleKitResizingBehaviorAspectFit typeColor: typeColor];
}

+ (void)drawPassphraseTypeWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing typeColor: (NSColor*)typeColor
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 250, 250), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 250, resizedFrame.size.height / 250);


    //// Bezier Drawing
    NSBezierPath* bezierPath = [NSBezierPath bezierPath];
    [bezierPath moveToPoint: NSMakePoint(235, 151.67)];
    [bezierPath curveToPoint: NSMakePoint(220, 136.67) controlPoint1: NSMakePoint(235, 143.42) controlPoint2: NSMakePoint(228.25, 136.67)];
    [bezierPath lineToPoint: NSMakePoint(30, 136.67)];
    [bezierPath curveToPoint: NSMakePoint(15, 151.67) controlPoint1: NSMakePoint(21.75, 136.67) controlPoint2: NSMakePoint(15, 143.42)];
    [bezierPath curveToPoint: NSMakePoint(30, 166.67) controlPoint1: NSMakePoint(15, 159.92) controlPoint2: NSMakePoint(21.75, 166.67)];
    [bezierPath lineToPoint: NSMakePoint(220, 166.67)];
    [bezierPath curveToPoint: NSMakePoint(235, 151.67) controlPoint1: NSMakePoint(228.25, 166.67) controlPoint2: NSMakePoint(235, 159.92)];
    [bezierPath closePath];
    [typeColor setStroke];
    bezierPath.lineWidth = 15;
    [bezierPath stroke];


    //// Bezier 2 Drawing
    NSBezierPath* bezier2Path = [NSBezierPath bezierPath];
    [bezier2Path moveToPoint: NSMakePoint(200, 205)];
    [bezier2Path curveToPoint: NSMakePoint(185, 190) controlPoint1: NSMakePoint(200, 196.75) controlPoint2: NSMakePoint(193.25, 190)];
    [bezier2Path lineToPoint: NSMakePoint(45, 190)];
    [bezier2Path curveToPoint: NSMakePoint(30, 205) controlPoint1: NSMakePoint(36.75, 190) controlPoint2: NSMakePoint(30, 196.75)];
    [bezier2Path curveToPoint: NSMakePoint(45, 220) controlPoint1: NSMakePoint(30, 213.25) controlPoint2: NSMakePoint(36.75, 220)];
    [bezier2Path lineToPoint: NSMakePoint(185, 220)];
    [bezier2Path curveToPoint: NSMakePoint(200, 205) controlPoint1: NSMakePoint(193.25, 220) controlPoint2: NSMakePoint(200, 213.25)];
    [bezier2Path closePath];
    [typeColor setStroke];
    bezier2Path.lineWidth = 15;
    [bezier2Path stroke];


    //// Bezier 3 Drawing
    NSBezierPath* bezier3Path = [NSBezierPath bezierPath];
    [bezier3Path moveToPoint: NSMakePoint(235, 97.76)];
    [bezier3Path curveToPoint: NSMakePoint(220.57, 83.33) controlPoint1: NSMakePoint(235, 89.82) controlPoint2: NSMakePoint(228.51, 83.33)];
    [bezier3Path lineToPoint: NSMakePoint(64.43, 83.33)];
    [bezier3Path curveToPoint: NSMakePoint(50, 97.76) controlPoint1: NSMakePoint(56.49, 83.33) controlPoint2: NSMakePoint(50, 89.82)];
    [bezier3Path lineToPoint: NSMakePoint(50, 98.91)];
    [bezier3Path curveToPoint: NSMakePoint(64.43, 113.33) controlPoint1: NSMakePoint(50, 106.84) controlPoint2: NSMakePoint(56.49, 113.33)];
    [bezier3Path lineToPoint: NSMakePoint(220.57, 113.33)];
    [bezier3Path curveToPoint: NSMakePoint(235, 98.91) controlPoint1: NSMakePoint(228.51, 113.33) controlPoint2: NSMakePoint(235, 106.84)];
    [bezier3Path lineToPoint: NSMakePoint(235, 97.76)];
    [bezier3Path closePath];
    [typeColor setStroke];
    bezier3Path.lineWidth = 15;
    [bezier3Path stroke];


    //// Bezier 4 Drawing
    NSBezierPath* bezier4Path = [NSBezierPath bezierPath];
    [bezier4Path moveToPoint: NSMakePoint(170, 45)];
    [bezier4Path curveToPoint: NSMakePoint(155, 30) controlPoint1: NSMakePoint(170, 36.75) controlPoint2: NSMakePoint(163.25, 30)];
    [bezier4Path lineToPoint: NSMakePoint(35, 30)];
    [bezier4Path curveToPoint: NSMakePoint(20, 45) controlPoint1: NSMakePoint(26.75, 30) controlPoint2: NSMakePoint(20, 36.75)];
    [bezier4Path curveToPoint: NSMakePoint(35, 60) controlPoint1: NSMakePoint(20, 53.25) controlPoint2: NSMakePoint(26.75, 60)];
    [bezier4Path lineToPoint: NSMakePoint(155, 60)];
    [bezier4Path curveToPoint: NSMakePoint(170, 45) controlPoint1: NSMakePoint(163.25, 60) controlPoint2: NSMakePoint(170, 53.25)];
    [bezier4Path closePath];
    [typeColor setStroke];
    bezier4Path.lineWidth = 15;
    [bezier4Path stroke];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawPatternTypeWithTypeColor: (NSColor*)typeColor
{
    [StyleKit drawPatternTypeWithFrame: NSMakeRect(0, 0, 250, 250) resizing: StyleKitResizingBehaviorAspectFit typeColor: typeColor];
}

+ (void)drawPatternTypeWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing typeColor: (NSColor*)typeColor
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 250, 250), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 250, resizedFrame.size.height / 250);


    //// Oval Drawing
    NSBezierPath* ovalPath = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(169.5, 27.1, 53.4, 53.4)];
    [typeColor setStroke];
    ovalPath.lineWidth = 15;
    [ovalPath stroke];


    //// Oval 2 Drawing
    NSBezierPath* oval2Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(169.5, 98.3, 53.4, 53.4)];
    [typeColor setStroke];
    oval2Path.lineWidth = 15;
    [oval2Path stroke];


    //// Oval 3 Drawing
    NSBezierPath* oval3Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(169.5, 169.5, 53.4, 53.4)];
    [typeColor setStroke];
    oval3Path.lineWidth = 15;
    [oval3Path stroke];


    //// Oval 4 Drawing
    NSBezierPath* oval4Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(98.3, 27.1, 53.4, 53.4)];
    [typeColor setStroke];
    oval4Path.lineWidth = 15;
    [oval4Path stroke];


    //// Oval 5 Drawing
    NSBezierPath* oval5Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(98.3, 98.3, 53.4, 53.4)];
    [typeColor setStroke];
    oval5Path.lineWidth = 15;
    [oval5Path stroke];


    //// Oval 6 Drawing
    NSBezierPath* oval6Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(98.3, 169.5, 53.4, 53.4)];
    [typeColor setStroke];
    oval6Path.lineWidth = 15;
    [oval6Path stroke];


    //// Oval 7 Drawing
    NSBezierPath* oval7Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(27.1, 27.1, 53.4, 53.4)];
    [typeColor setStroke];
    oval7Path.lineWidth = 15;
    [oval7Path stroke];


    //// Oval 8 Drawing
    NSBezierPath* oval8Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(27.1, 98.3, 53.4, 53.4)];
    [typeColor setStroke];
    oval8Path.lineWidth = 15;
    [oval8Path stroke];


    //// Oval 9 Drawing
    NSBezierPath* oval9Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(27.1, 169.5, 53.4, 53.4)];
    [typeColor setStroke];
    oval9Path.lineWidth = 15;
    [oval9Path stroke];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawPronounceableTypeWithTypeColor: (NSColor*)typeColor
{
    [StyleKit drawPronounceableTypeWithFrame: NSMakeRect(0, 0, 250, 250) resizing: StyleKitResizingBehaviorAspectFit typeColor: typeColor];
}

+ (void)drawPronounceableTypeWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing typeColor: (NSColor*)typeColor
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 250, 250), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 250, resizedFrame.size.height / 250);


    //// Bezier Drawing
    NSBezierPath* bezierPath = [NSBezierPath bezierPath];
    [bezierPath moveToPoint: NSMakePoint(125.55, 205.8)];
    [bezierPath curveToPoint: NSMakePoint(30.55, 130.8) controlPoint1: NSMakePoint(73.08, 205.8) controlPoint2: NSMakePoint(30.55, 172.22)];
    [bezierPath curveToPoint: NSMakePoint(65.12, 72.93) controlPoint1: NSMakePoint(30.55, 107.5) controlPoint2: NSMakePoint(44, 86.69)];
    [bezierPath curveToPoint: NSMakePoint(30.55, 45.8) controlPoint1: NSMakePoint(51.83, 56.74) controlPoint2: NSMakePoint(23.57, 47.2)];
    [bezierPath curveToPoint: NSMakePoint(105.37, 57.5) controlPoint1: NSMakePoint(55.97, 40.72) controlPoint2: NSMakePoint(83.98, 48.56)];
    [bezierPath curveToPoint: NSMakePoint(125.55, 55.8) controlPoint1: NSMakePoint(111.88, 56.39) controlPoint2: NSMakePoint(118.62, 55.8)];
    [bezierPath curveToPoint: NSMakePoint(220.55, 130.8) controlPoint1: NSMakePoint(178.01, 55.8) controlPoint2: NSMakePoint(220.55, 89.38)];
    [bezierPath curveToPoint: NSMakePoint(125.55, 205.8) controlPoint1: NSMakePoint(220.55, 172.22) controlPoint2: NSMakePoint(178.01, 205.8)];
    [bezierPath closePath];
    [typeColor setStroke];
    bezierPath.lineWidth = 15;
    [bezierPath stroke];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawRandomTypeWithTypeColor: (NSColor*)typeColor
{
    [StyleKit drawRandomTypeWithFrame: NSMakeRect(0, 0, 250, 250) resizing: StyleKitResizingBehaviorAspectFit typeColor: typeColor];
}

+ (void)drawRandomTypeWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing typeColor: (NSColor*)typeColor
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 250, 250), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 250, resizedFrame.size.height / 250);


    //// Rectangle Drawing
    NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRect: NSMakeRect(65.75, 184.25, 39.5, 39.5)];
    [typeColor setStroke];
    rectanglePath.lineWidth = 15;
    [rectanglePath stroke];


    //// Bezier Drawing
    NSBezierPath* bezierPath = [NSBezierPath bezierPath];
    [bezierPath moveToPoint: NSMakePoint(184.25, 105.25)];
    [bezierPath lineToPoint: NSMakePoint(144.75, 105.25)];
    [bezierPath lineToPoint: NSMakePoint(144.75, 144.75)];
    [bezierPath lineToPoint: NSMakePoint(184.25, 144.75)];
    [bezierPath lineToPoint: NSMakePoint(184.25, 105.25)];
    [bezierPath closePath];
    [bezierPath moveToPoint: NSMakePoint(184.25, 184.25)];
    [bezierPath lineToPoint: NSMakePoint(184.25, 223.75)];
    [bezierPath lineToPoint: NSMakePoint(144.75, 223.75)];
    [bezierPath lineToPoint: NSMakePoint(144.75, 184.25)];
    [bezierPath lineToPoint: NSMakePoint(105.25, 184.25)];
    [bezierPath lineToPoint: NSMakePoint(105.25, 144.75)];
    [bezierPath lineToPoint: NSMakePoint(65.75, 144.75)];
    [bezierPath lineToPoint: NSMakePoint(65.75, 105.25)];
    [bezierPath lineToPoint: NSMakePoint(26.25, 105.25)];
    [bezierPath lineToPoint: NSMakePoint(26.25, 65.75)];
    [bezierPath lineToPoint: NSMakePoint(65.75, 65.75)];
    [bezierPath lineToPoint: NSMakePoint(65.75, 26.25)];
    [bezierPath lineToPoint: NSMakePoint(105.25, 26.25)];
    [bezierPath lineToPoint: NSMakePoint(105.25, 65.75)];
    [bezierPath lineToPoint: NSMakePoint(144.75, 65.75)];
    [bezierPath lineToPoint: NSMakePoint(144.75, 26.25)];
    [bezierPath lineToPoint: NSMakePoint(184.25, 26.25)];
    [bezierPath lineToPoint: NSMakePoint(184.25, 65.75)];
    [bezierPath lineToPoint: NSMakePoint(223.75, 65.75)];
    [bezierPath lineToPoint: NSMakePoint(223.75, 105.25)];
    [bezierPath lineToPoint: NSMakePoint(223.75, 144.75)];
    [bezierPath lineToPoint: NSMakePoint(223.75, 184.25)];
    [bezierPath lineToPoint: NSMakePoint(184.25, 184.25)];
    [bezierPath closePath];
    [typeColor setStroke];
    bezierPath.lineWidth = 15;
    [bezierPath stroke];


    //// Rectangle 2 Drawing
    NSBezierPath* rectangle2Path = [NSBezierPath bezierPathWithRect: NSMakeRect(26.25, 144.75, 39.5, 39.5)];
    [typeColor setStroke];
    rectangle2Path.lineWidth = 15;
    [rectangle2Path stroke];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawStoredTypeWithTypeColor: (NSColor*)typeColor
{
    [StyleKit drawStoredTypeWithFrame: NSMakeRect(0, 0, 250, 250) resizing: StyleKitResizingBehaviorAspectFit typeColor: typeColor];
}

+ (void)drawStoredTypeWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing typeColor: (NSColor*)typeColor
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 250, 250), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 250, resizedFrame.size.height / 250);


    //// Oval Drawing
    NSBezierPath* ovalPath = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(25, 25, 200, 200)];
    [typeColor setStroke];
    ovalPath.lineWidth = 15;
    [ovalPath stroke];


    //// Oval 2 Drawing
    NSBezierPath* oval2Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(95, 95, 60, 60)];
    [typeColor setStroke];
    oval2Path.lineWidth = 15;
    [oval2Path stroke];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawZoom1
{
    [StyleKit drawZoom1WithFrame: NSMakeRect(0, 0, 21, 21) resizing: StyleKitResizingBehaviorAspectFit];
}

+ (void)drawZoom1WithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 21, 21), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 21, resizedFrame.size.height / 21);


    //// Color Declarations
    NSColor* iconStroke = [NSColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];

    //// Oval Drawing
    NSBezierPath* ovalPath = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(2.5, 2.5, 16, 16)];
    [iconStroke setStroke];
    ovalPath.lineWidth = 1;
    [ovalPath stroke];


    //// Bezier Drawing
    NSBezierPath* bezierPath = [NSBezierPath bezierPath];
    [bezierPath moveToPoint: NSMakePoint(6.35, 6.35)];
    [bezierPath lineToPoint: NSMakePoint(9.18, 9.18)];
    [iconStroke setStroke];
    bezierPath.lineWidth = 2;
    [bezierPath stroke];


    //// Oval 2 Drawing
    NSBezierPath* oval2Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(8.25, 8.25, 6.4, 6.4)];
    [iconStroke setStroke];
    oval2Path.lineWidth = 1;
    [oval2Path stroke];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawZoom
{
    [StyleKit drawZoomWithFrame: NSMakeRect(0, 0, 21, 21) resizing: StyleKitResizingBehaviorAspectFit];
}

+ (void)drawZoomWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 21, 21), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 21, resizedFrame.size.height / 21);


    //// Color Declarations
    NSColor* iconStroke = [NSColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];

    //// Oval Drawing
    NSBezierPath* ovalPath = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(2.5, 2.5, 16, 16)];
    [iconStroke setStroke];
    ovalPath.lineWidth = 1;
    [ovalPath stroke];


    //// Bezier Drawing
    NSBezierPath* bezierPath = [NSBezierPath bezierPath];
    [bezierPath moveToPoint: NSMakePoint(6.35, 6.35)];
    [bezierPath lineToPoint: NSMakePoint(9.18, 9.18)];
    [iconStroke setStroke];
    bezierPath.lineWidth = 2;
    [bezierPath stroke];


    //// Oval 2 Drawing
    NSBezierPath* oval2Path = [NSBezierPath bezierPathWithOvalInRect: NSMakeRect(8.25, 8.25, 6.4, 6.4)];
    [iconStroke setStroke];
    oval2Path.lineWidth = 1;
    [oval2Path stroke];


    //// Bezier 2 Drawing
    NSBezierPath* bezier2Path = [NSBezierPath bezierPath];
    [bezier2Path moveToPoint: NSMakePoint(11.45, 13.01)];
    [bezier2Path lineToPoint: NSMakePoint(11.45, 9.89)];
    [iconStroke setStroke];
    bezier2Path.lineWidth = 0.75;
    [bezier2Path stroke];


    //// Bezier 3 Drawing
    NSBezierPath* bezier3Path = [NSBezierPath bezierPath];
    [bezier3Path moveToPoint: NSMakePoint(13, 11.45)];
    [bezier3Path lineToPoint: NSMakePoint(9.89, 11.45)];
    [iconStroke setStroke];
    bezier3Path.lineWidth = 0.75;
    [bezier3Path stroke];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawPasswordHeader
{
    [StyleKit drawPasswordHeaderWithFrame: NSMakeRect(0, 0, 80, 20) resizing: StyleKitResizingBehaviorAspectFit];
}

+ (void)drawPasswordHeaderWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 80, 20), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 80, resizedFrame.size.height / 20);


    //// Color Declarations
    NSColor* headerColor = [NSColor colorWithRed: 0.345 green: 0.349 blue: 0.357 alpha: 1];

    //// Rectangle Drawing
    NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRoundedRect: NSMakeRect(1.75, 2.47, 76.5, 15.05) xRadius: 7.4 yRadius: 7.4];
    [headerColor setStroke];
    rectanglePath.lineWidth = 1;
    [rectanglePath stroke];


    //// Bezier Drawing
    NSBezierPath* bezierPath = [NSBezierPath bezierPath];
    [bezierPath moveToPoint: NSMakePoint(21.5, 8.58)];
    [bezierPath lineToPoint: NSMakePoint(20.98, 7.7)];
    [bezierPath lineToPoint: NSMakePoint(18.89, 9.08)];
    [bezierPath lineToPoint: NSMakePoint(18.89, 6.56)];
    [bezierPath lineToPoint: NSMakePoint(17.92, 6.56)];
    [bezierPath lineToPoint: NSMakePoint(17.92, 9.08)];
    [bezierPath lineToPoint: NSMakePoint(15.81, 7.68)];
    [bezierPath lineToPoint: NSMakePoint(15.29, 8.58)];
    [bezierPath lineToPoint: NSMakePoint(17.5, 10.02)];
    [bezierPath lineToPoint: NSMakePoint(15.29, 11.46)];
    [bezierPath lineToPoint: NSMakePoint(15.81, 12.34)];
    [bezierPath lineToPoint: NSMakePoint(17.92, 10.93)];
    [bezierPath lineToPoint: NSMakePoint(17.92, 13.44)];
    [bezierPath lineToPoint: NSMakePoint(18.89, 13.44)];
    [bezierPath lineToPoint: NSMakePoint(18.89, 10.95)];
    [bezierPath lineToPoint: NSMakePoint(20.98, 12.34)];
    [bezierPath lineToPoint: NSMakePoint(21.5, 11.46)];
    [bezierPath lineToPoint: NSMakePoint(19.32, 10.02)];
    [bezierPath lineToPoint: NSMakePoint(21.5, 8.58)];
    [bezierPath closePath];
    [headerColor setFill];
    [bezierPath fill];


    //// Bezier 2 Drawing
    NSBezierPath* bezier2Path = [NSBezierPath bezierPath];
    [bezier2Path moveToPoint: NSMakePoint(32.31, 8.58)];
    [bezier2Path lineToPoint: NSMakePoint(31.78, 7.7)];
    [bezier2Path lineToPoint: NSMakePoint(29.7, 9.08)];
    [bezier2Path lineToPoint: NSMakePoint(29.7, 6.56)];
    [bezier2Path lineToPoint: NSMakePoint(28.72, 6.56)];
    [bezier2Path lineToPoint: NSMakePoint(28.72, 9.08)];
    [bezier2Path lineToPoint: NSMakePoint(26.61, 7.68)];
    [bezier2Path lineToPoint: NSMakePoint(26.09, 8.58)];
    [bezier2Path lineToPoint: NSMakePoint(28.31, 10.02)];
    [bezier2Path lineToPoint: NSMakePoint(26.09, 11.46)];
    [bezier2Path lineToPoint: NSMakePoint(26.61, 12.34)];
    [bezier2Path lineToPoint: NSMakePoint(28.72, 10.93)];
    [bezier2Path lineToPoint: NSMakePoint(28.72, 13.44)];
    [bezier2Path lineToPoint: NSMakePoint(29.7, 13.44)];
    [bezier2Path lineToPoint: NSMakePoint(29.7, 10.95)];
    [bezier2Path lineToPoint: NSMakePoint(31.78, 12.34)];
    [bezier2Path lineToPoint: NSMakePoint(32.31, 11.46)];
    [bezier2Path lineToPoint: NSMakePoint(30.13, 10.02)];
    [bezier2Path lineToPoint: NSMakePoint(32.31, 8.58)];
    [bezier2Path closePath];
    [headerColor setFill];
    [bezier2Path fill];


    //// Bezier 3 Drawing
    NSBezierPath* bezier3Path = [NSBezierPath bezierPath];
    [bezier3Path moveToPoint: NSMakePoint(43.11, 8.58)];
    [bezier3Path lineToPoint: NSMakePoint(42.58, 7.7)];
    [bezier3Path lineToPoint: NSMakePoint(40.5, 9.08)];
    [bezier3Path lineToPoint: NSMakePoint(40.5, 6.56)];
    [bezier3Path lineToPoint: NSMakePoint(39.52, 6.56)];
    [bezier3Path lineToPoint: NSMakePoint(39.52, 9.08)];
    [bezier3Path lineToPoint: NSMakePoint(37.41, 7.68)];
    [bezier3Path lineToPoint: NSMakePoint(36.89, 8.58)];
    [bezier3Path lineToPoint: NSMakePoint(39.11, 10.02)];
    [bezier3Path lineToPoint: NSMakePoint(36.89, 11.46)];
    [bezier3Path lineToPoint: NSMakePoint(37.41, 12.34)];
    [bezier3Path lineToPoint: NSMakePoint(39.52, 10.93)];
    [bezier3Path lineToPoint: NSMakePoint(39.52, 13.44)];
    [bezier3Path lineToPoint: NSMakePoint(40.5, 13.44)];
    [bezier3Path lineToPoint: NSMakePoint(40.5, 10.95)];
    [bezier3Path lineToPoint: NSMakePoint(42.58, 12.34)];
    [bezier3Path lineToPoint: NSMakePoint(43.11, 11.46)];
    [bezier3Path lineToPoint: NSMakePoint(40.93, 10.02)];
    [bezier3Path lineToPoint: NSMakePoint(43.11, 8.58)];
    [bezier3Path closePath];
    [headerColor setFill];
    [bezier3Path fill];


    //// Bezier 4 Drawing
    NSBezierPath* bezier4Path = [NSBezierPath bezierPath];
    [bezier4Path moveToPoint: NSMakePoint(53.91, 8.58)];
    [bezier4Path lineToPoint: NSMakePoint(53.38, 7.7)];
    [bezier4Path lineToPoint: NSMakePoint(51.3, 9.08)];
    [bezier4Path lineToPoint: NSMakePoint(51.3, 6.56)];
    [bezier4Path lineToPoint: NSMakePoint(50.32, 6.56)];
    [bezier4Path lineToPoint: NSMakePoint(50.32, 9.08)];
    [bezier4Path lineToPoint: NSMakePoint(48.21, 7.68)];
    [bezier4Path lineToPoint: NSMakePoint(47.7, 8.58)];
    [bezier4Path lineToPoint: NSMakePoint(49.91, 10.02)];
    [bezier4Path lineToPoint: NSMakePoint(47.7, 11.46)];
    [bezier4Path lineToPoint: NSMakePoint(48.21, 12.34)];
    [bezier4Path lineToPoint: NSMakePoint(50.32, 10.93)];
    [bezier4Path lineToPoint: NSMakePoint(50.32, 13.44)];
    [bezier4Path lineToPoint: NSMakePoint(51.3, 13.44)];
    [bezier4Path lineToPoint: NSMakePoint(51.3, 10.95)];
    [bezier4Path lineToPoint: NSMakePoint(53.38, 12.34)];
    [bezier4Path lineToPoint: NSMakePoint(53.91, 11.46)];
    [bezier4Path lineToPoint: NSMakePoint(51.73, 10.02)];
    [bezier4Path lineToPoint: NSMakePoint(53.91, 8.58)];
    [bezier4Path closePath];
    [headerColor setFill];
    [bezier4Path fill];


    //// Bezier 5 Drawing
    NSBezierPath* bezier5Path = [NSBezierPath bezierPath];
    [bezier5Path moveToPoint: NSMakePoint(64.71, 8.58)];
    [bezier5Path lineToPoint: NSMakePoint(64.18, 7.7)];
    [bezier5Path lineToPoint: NSMakePoint(62.1, 9.08)];
    [bezier5Path lineToPoint: NSMakePoint(62.1, 6.56)];
    [bezier5Path lineToPoint: NSMakePoint(61.12, 6.56)];
    [bezier5Path lineToPoint: NSMakePoint(61.12, 9.08)];
    [bezier5Path lineToPoint: NSMakePoint(59.02, 7.68)];
    [bezier5Path lineToPoint: NSMakePoint(58.5, 8.58)];
    [bezier5Path lineToPoint: NSMakePoint(60.71, 10.02)];
    [bezier5Path lineToPoint: NSMakePoint(58.5, 11.46)];
    [bezier5Path lineToPoint: NSMakePoint(59.02, 12.34)];
    [bezier5Path lineToPoint: NSMakePoint(61.12, 10.93)];
    [bezier5Path lineToPoint: NSMakePoint(61.12, 13.44)];
    [bezier5Path lineToPoint: NSMakePoint(62.1, 13.44)];
    [bezier5Path lineToPoint: NSMakePoint(62.1, 10.95)];
    [bezier5Path lineToPoint: NSMakePoint(64.18, 12.34)];
    [bezier5Path lineToPoint: NSMakePoint(64.71, 11.46)];
    [bezier5Path lineToPoint: NSMakePoint(62.53, 10.02)];
    [bezier5Path lineToPoint: NSMakePoint(64.71, 8.58)];
    [bezier5Path closePath];
    [headerColor setFill];
    [bezier5Path fill];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawPasswordStrengthHeader
{
    [StyleKit drawPasswordStrengthHeaderWithFrame: NSMakeRect(0, 0, 20, 20) resizing: StyleKitResizingBehaviorAspectFit];
}

+ (void)drawPasswordStrengthHeaderWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 20, 20), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 20, resizedFrame.size.height / 20);


    //// Color Declarations
    NSColor* headerColor = [NSColor colorWithRed: 0.345 green: 0.349 blue: 0.357 alpha: 1];

    //// Rectangle Drawing
    NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRoundedRect: NSMakeRect(13.7, 4.15, 3.1, 11.7) xRadius: 1.4 yRadius: 1.4];
    [headerColor setStroke];
    rectanglePath.lineWidth = 1;
    [rectanglePath stroke];


    //// Rectangle 2 Drawing
    NSBezierPath* rectangle2Path = [NSBezierPath bezierPathWithRoundedRect: NSMakeRect(13.7, 4.15, 3.1, 11.7) xRadius: 1.4 yRadius: 1.4];
    [headerColor setStroke];
    rectangle2Path.lineWidth = 1;
    [rectangle2Path stroke];


    //// Rectangle 3 Drawing
    NSBezierPath* rectangle3Path = [NSBezierPath bezierPathWithRoundedRect: NSMakeRect(8.45, 4.18, 3.1, 7.45) xRadius: 1.4 yRadius: 1.4];
    [headerColor setStroke];
    rectangle3Path.lineWidth = 1;
    [rectangle3Path stroke];


    //// Rectangle 4 Drawing
    NSBezierPath* rectangle4Path = [NSBezierPath bezierPathWithRoundedRect: NSMakeRect(8.45, 4.18, 3.1, 7.45) xRadius: 1.4 yRadius: 1.4];
    [headerColor setStroke];
    rectangle4Path.lineWidth = 1;
    [rectangle4Path stroke];


    //// Rectangle 5 Drawing
    NSBezierPath* rectangle5Path = [NSBezierPath bezierPathWithRoundedRect: NSMakeRect(3.2, 4.15, 3.1, 3.2) xRadius: 1.4 yRadius: 1.4];
    [headerColor setStroke];
    rectangle5Path.lineWidth = 1;
    [rectangle5Path stroke];


    //// Rectangle 6 Drawing
    NSBezierPath* rectangle6Path = [NSBezierPath bezierPathWithRoundedRect: NSMakeRect(3.2, 4.15, 3.1, 3.2) xRadius: 1.4 yRadius: 1.4];
    [headerColor setStroke];
    rectangle6Path.lineWidth = 1;
    [rectangle6Path stroke];
    
    [NSGraphicsContext restoreGraphicsState];

}

+ (void)drawPasswordTypeHeader
{
    [StyleKit drawPasswordTypeHeaderWithFrame: NSMakeRect(0, 0, 20, 20) resizing: StyleKitResizingBehaviorAspectFit];
}

+ (void)drawPasswordTypeHeaderWithFrame: (NSRect)targetFrame resizing: (StyleKitResizingBehavior)resizing
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;
    
    //// Resize to Target Frame
    [NSGraphicsContext saveGraphicsState];
    NSRect resizedFrame = StyleKitResizingBehaviorApply(resizing, NSMakeRect(0, 0, 20, 20), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 20, resizedFrame.size.height / 20);


    //// Color Declarations
    NSColor* headerColor = [NSColor colorWithRed: 0.345 green: 0.349 blue: 0.357 alpha: 1];

    //// Star Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 6.8, 8.15);
    CGContextRotateCTM(context, 30.15 * M_PI/180);

    NSBezierPath* starPath = [NSBezierPath bezierPath];
    [starPath moveToPoint: NSMakePoint(0, 6.4)];
    [starPath lineToPoint: NSMakePoint(3.7, 0)];
    [starPath lineToPoint: NSMakePoint(0, -6.4)];
    [starPath lineToPoint: NSMakePoint(-3.7, -0)];
    [starPath closePath];
    [headerColor setStroke];
    starPath.lineWidth = 1;
    starPath.lineJoinStyle = NSRoundLineJoinStyle;
    [starPath stroke];

    [NSGraphicsContext restoreGraphicsState];


    //// Star 2 Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 13.2, 8.15);
    CGContextRotateCTM(context, 149.85 * M_PI/180);

    NSBezierPath* star2Path = [NSBezierPath bezierPath];
    [star2Path moveToPoint: NSMakePoint(0, 6.4)];
    [star2Path lineToPoint: NSMakePoint(3.65, 0)];
    [star2Path lineToPoint: NSMakePoint(0, -6.4)];
    [star2Path lineToPoint: NSMakePoint(-3.65, -0)];
    [star2Path closePath];
    [headerColor setStroke];
    star2Path.lineWidth = 1;
    star2Path.lineJoinStyle = NSRoundLineJoinStyle;
    [star2Path stroke];

    [NSGraphicsContext restoreGraphicsState];


    //// Star 3 Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, 10, 13.65);
    CGContextRotateCTM(context, 90 * M_PI/180);

    NSBezierPath* star3Path = [NSBezierPath bezierPath];
    [star3Path moveToPoint: NSMakePoint(0, 6.45)];
    [star3Path lineToPoint: NSMakePoint(3.7, 0)];
    [star3Path lineToPoint: NSMakePoint(0, -6.45)];
    [star3Path lineToPoint: NSMakePoint(-3.7, -0)];
    [star3Path closePath];
    [headerColor setStroke];
    star3Path.lineWidth = 1;
    star3Path.lineJoinStyle = NSRoundLineJoinStyle;
    [star3Path stroke];

    [NSGraphicsContext restoreGraphicsState];
    
    [NSGraphicsContext restoreGraphicsState];

}

#pragma mark Generated Images

+ (NSImage*)imageOfPreferencesButton
{
    if (_imageOfPreferencesButton)
        return _imageOfPreferencesButton;

    _imageOfPreferencesButton = [NSImage imageWithSize: NSMakeSize(42, 42) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawPreferencesButton];

        return YES;
    }];

    return _imageOfPreferencesButton;
}

+ (NSImage*)imageOfMenuIcon
{
    if (_imageOfMenuIcon)
        return _imageOfMenuIcon;

    _imageOfMenuIcon = [NSImage imageWithSize: NSMakeSize(32, 32) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawMenuIcon];

        return YES;
    }];

    return _imageOfMenuIcon;
}

+ (NSImage*)imageOfAdvancedTypeWithTypeColor: (NSColor*)typeColor
{
    return [NSImage imageWithSize: NSMakeSize(250, 250) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawAdvancedTypeWithTypeColor: typeColor];

        return YES;
    }];
}

+ (NSImage*)imageOfPassphraseTypeWithTypeColor: (NSColor*)typeColor
{
    return [NSImage imageWithSize: NSMakeSize(250, 250) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawPassphraseTypeWithTypeColor: typeColor];

        return YES;
    }];
}

+ (NSImage*)imageOfPatternTypeWithTypeColor: (NSColor*)typeColor
{
    return [NSImage imageWithSize: NSMakeSize(250, 250) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawPatternTypeWithTypeColor: typeColor];

        return YES;
    }];
}

+ (NSImage*)imageOfPronounceableTypeWithTypeColor: (NSColor*)typeColor
{
    return [NSImage imageWithSize: NSMakeSize(250, 250) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawPronounceableTypeWithTypeColor: typeColor];

        return YES;
    }];
}

+ (NSImage*)imageOfRandomTypeWithTypeColor: (NSColor*)typeColor
{
    return [NSImage imageWithSize: NSMakeSize(250, 250) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawRandomTypeWithTypeColor: typeColor];

        return YES;
    }];
}

+ (NSImage*)imageOfStoredTypeWithTypeColor: (NSColor*)typeColor
{
    return [NSImage imageWithSize: NSMakeSize(250, 250) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawStoredTypeWithTypeColor: typeColor];

        return YES;
    }];
}

+ (NSImage*)imageOfZoom1
{
    if (_imageOfZoom1)
        return _imageOfZoom1;

    _imageOfZoom1 = [NSImage imageWithSize: NSMakeSize(21, 21) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawZoom1];

        return YES;
    }];

    return _imageOfZoom1;
}

+ (NSImage*)imageOfZoom
{
    if (_imageOfZoom)
        return _imageOfZoom;

    _imageOfZoom = [NSImage imageWithSize: NSMakeSize(21, 21) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawZoom];

        return YES;
    }];

    return _imageOfZoom;
}

+ (NSImage*)imageOfPasswordHeader
{
    if (_imageOfPasswordHeader)
        return _imageOfPasswordHeader;

    _imageOfPasswordHeader = [NSImage imageWithSize: NSMakeSize(80, 20) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawPasswordHeader];

        return YES;
    }];

    return _imageOfPasswordHeader;
}

+ (NSImage*)imageOfPasswordStrengthHeader
{
    if (_imageOfPasswordStrengthHeader)
        return _imageOfPasswordStrengthHeader;

    _imageOfPasswordStrengthHeader = [NSImage imageWithSize: NSMakeSize(20, 20) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawPasswordStrengthHeader];

        return YES;
    }];

    return _imageOfPasswordStrengthHeader;
}

+ (NSImage*)imageOfPasswordTypeHeader
{
    if (_imageOfPasswordTypeHeader)
        return _imageOfPasswordTypeHeader;

    _imageOfPasswordTypeHeader = [NSImage imageWithSize: NSMakeSize(20, 20) flipped: NO drawingHandler: ^(__unused NSRect dstRect)
    {
        [StyleKit drawPasswordTypeHeader];

        return YES;
    }];

    return _imageOfPasswordTypeHeader;
}

@end



NSRect StyleKitResizingBehaviorApply(StyleKitResizingBehavior behavior, NSRect rect, NSRect target)
{
    if (NSEqualRects(rect, target) || NSEqualRects(target, NSZeroRect))
        return rect;

    NSSize scales = NSZeroSize;
    scales.width = ABS(target.size.width / rect.size.width);
    scales.height = ABS(target.size.height / rect.size.height);

    switch (behavior)
    {
        case StyleKitResizingBehaviorAspectFit:
        {
            scales.width = MIN(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case StyleKitResizingBehaviorAspectFill:
        {
            scales.width = MAX(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case StyleKitResizingBehaviorStretch:
            break;
        case StyleKitResizingBehaviorCenter:
        {
            scales.width = 1;
            scales.height = 1;
            break;
        }
    }

    NSRect result = CGRectStandardize(rect);
    result.size.width *= scales.width;
    result.size.height *= scales.height;
    result.origin.x = target.origin.x + (target.size.width - result.size.width) / 2;
    result.origin.y = target.origin.y + (target.size.height - result.size.height) / 2;
    return result;
}
