//
//  StyleKit.h
//  Password Factory
//
//  Created by Cristiana Yambo on 1/15/16.
//  Copyright (c) 2016 Cloud13. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface StyleKit : NSObject

// Colors
+ (NSColor*)strengthColors;

// Drawing Methods
+ (void)drawStrengthMeterWithStrengthColor: (NSColor*)strengthColor strength: (CGFloat)strength;
+ (void)drawPreferencesButton;
+ (void)drawMenuIcon;
+ (void)drawStrengthBoxWithStrengthColor: (NSColor*)strengthColor;

// Generated Images
+ (NSImage*)imageOfPreferencesButton;
+ (NSImage*)imageOfMenuIcon;

@end
