//
//  StyleKit.h
//  Password Factory
//
//  Created by Cristiana Yambo on 8/15/15.
//  Copyright (c) 2015 Cloud13. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface StyleKit : NSObject

// Colors
+ (NSColor*)strengthColors;

// Drawing Methods
+ (void)drawStrengthMeterWithStrengthColor: (NSColor*)strengthColor strength: (CGFloat)strength;
+ (void)drawPreferencesButton;

// Generated Images
+ (NSImage*)imageOfPreferencesButton;

@end
