//
//  StyleKit.m
//  Password Factory
//
//  Created by Cristiana Yambo on 8/15/15.
//  Copyright (c) 2015 Cloud13. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKit.h"


@implementation StyleKit

#pragma mark Cache

static NSColor* _strengthColors = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _strengthColors = [NSColor colorWithCalibratedRed: 0.848 green: 0.077 blue: 0.077 alpha: 1];

}

#pragma mark Colors

+ (NSColor*)strengthColors { return _strengthColors; }

#pragma mark Drawing Methods

+ (void)drawStrengthMeterWithStrengthColor: (NSColor*)strengthColor strength: (CGFloat)strength
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;

    //// Color Declarations
    NSColor* baseFill = [NSColor colorWithCalibratedRed: 1 green: 1 blue: 1 alpha: 1];
    NSColor* borderColor = [NSColor colorWithCalibratedRed: 0.694 green: 0.694 blue: 0.694 alpha: 1];

    //// Meter Background Drawing
    NSBezierPath* meterBackgroundPath = [NSBezierPath bezierPathWithRect: NSMakeRect(0, 0, 212, 21)];
    [baseFill setFill];
    [meterBackgroundPath fill];
    [borderColor setStroke];
    [meterBackgroundPath setLineWidth: 2];
    [meterBackgroundPath stroke];


    //// Meter Color Drawing
    [NSGraphicsContext saveGraphicsState];
    CGContextTranslateCTM(context, -0.68, 0);
    CGContextScaleCTM(context, strength, 1);

    NSBezierPath* meterColorPath = [NSBezierPath bezierPathWithRect: NSMakeRect(1, 0, 212, 21)];
    [strengthColor setFill];
    [meterColorPath fill];

    [NSGraphicsContext restoreGraphicsState];
}

@end
